'use client';
import { useState, useEffect } from 'react';
import Link from 'next/link';

export default function TermsPage() {
  const [lang, setLang] = useState('vi');
  useEffect(() => { const s = localStorage.getItem('marketplace_lang') || localStorage.getItem('ovenly_language') || 'vi'; setLang(s); }, []);
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white border-b border-gray-200 sticky top-0 z-40">
        <div className="max-w-4xl mx-auto px-4 h-14 flex items-center justify-between">
          <Link href="/" className="font-heading font-black text-primary text-lg">LÒ ĐỒ ĂN</Link>
          <div className="flex items-center bg-gray-100 rounded-full p-0.5 text-xs font-bold">
            <button onClick={() => setLang('vi')} className={`px-3 py-1 rounded-full transition-all ${lang === 'vi' ? 'bg-primary text-white' : 'text-gray-500'}`}>VI</button>
            <button onClick={() => setLang('en')} className={`px-3 py-1 rounded-full transition-all ${lang === 'en' ? 'bg-primary text-white' : 'text-gray-500'}`}>EN</button>
          </div>
        </div>
      </header>
      <div className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="font-heading text-3xl font-black text-primary mb-8">{lang === 'vi' ? 'Điều Khoản Dịch Vụ' : 'Terms of Service'}</h1>
        <div className="bg-white rounded-2xl p-8 space-y-6 text-gray-700 leading-relaxed" style={{ boxShadow: '0 1px 4px rgba(0,0,0,0.06)' }}>
          <p className="text-sm text-gray-400">{lang === 'vi' ? 'Cập nhật lần cuối: Tháng 4 năm 2026' : 'Last updated: April 2026'}</p>
          {lang === 'vi' ? (<>
            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">1. Giới Thiệu và Chấp Nhận Điều Khoản</h2><p className="mb-3">Vui lòng đọc kỹ Điều Khoản Dịch Vụ này. Bằng việc truy cập và sử dụng nền tảng LÒ ĐỒ ĂN ("Nền Tảng"), bạn đồng ý rằng bạn đã đọc, hiểu và chấp nhận bị ràng buộc bởi các điều khoản này.</p><p className="mb-3"><strong>Ovenly</strong> là công ty công nghệ cung cấp và vận hành Nền Tảng LÒ ĐỒ ĂN. Khi được đề cập trong văn bản này, "chúng tôi", "của chúng tôi" hoặc "Ovenly" đều ám chỉ đến công ty Ovenly.</p><p><strong>QUAN TRỌNG: OVENLY LÀ NỀN TẢNG CÔNG NGHỆ</strong> kết nối khách hàng với các nhà hàng đối tác. OVENLY KHÔNG PHẢI LÀ NHÀ HÀNG, KHÔNG TỰ CHẾ BIẾN THỰC PHẨM, VÀ KHÔNG PHẢI LÀ BÊN BÁN HÀNG TRỰC TIẾP. Vai trò của Ovenly là cung cấp nền tảng để khách hàng đặt hàng từ các nhà hàng độc lập.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">2. Định Nghĩa</h2><ul className="list-disc list-inside space-y-2"><li><strong>Nền Tảng:</strong> Ứng dụng web và di động LÒ ĐỒ ĂN do Ovenly cung cấp</li><li><strong>Người Dùng:</strong> Khách hàng sử dụng Nền Tảng để đặt hàng thực phẩm</li><li><strong>Nhà Hàng:</strong> Các cơ sở kinh doanh thực phẩm đăng ký bán hàng trên Nền Tảng</li><li><strong>Đơn Hàng:</strong> Yêu cầu mua thực phẩm được đặt qua Nền Tảng</li><li><strong>Phí Dịch Vụ:</strong> Phí Ovenly thu để duy trì và vận hành Nền Tảng</li><li><strong>Dữ Liệu Cá Nhân:</strong> Thông tin có thể nhận dạng cá nhân theo Luật Bảo Vệ Dữ Liệu Cá Nhân</li></ul></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">3. Yêu Cầu Độ Tuổi và Năng Lực Pháp Lý</h2><p>Bạn phải đủ 18 tuổi trở lên để sử dụng Nền Tảng. Bằng việc sử dụng dịch vụ, bạn cam đoan rằng bạn có đầy đủ năng lực pháp lý để ký kết hợp đồng theo pháp luật Việt Nam.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">4. Cam Đoan và Nghĩa Vụ Của Người Dùng</h2><p className="mb-2">Khi sử dụng Nền Tảng, bạn cam đoan và đồng ý rằng:</p><ul className="list-disc list-inside space-y-2"><li>Tất cả thông tin bạn cung cấp là đúng, chính xác và đầy đủ</li><li>Bạn sẽ bảo mật mật khẩu tài khoản và thông báo ngay cho chúng tôi nếu có sử dụng trái phép</li><li>Bạn chỉ sử dụng Nền Tảng cho mục đích hợp pháp và cá nhân</li><li>Bạn sẽ không cố gắng gây gián đoạn, làm tổn hại hoặc truy cập trái phép vào Nền Tảng</li><li>Bạn sẽ không sử dụng Nền Tảng để gửi nội dung trái pháp luật, vi phạm đạo đức hoặc gây hại cho người khác</li><li>Bạn chỉ tạo một (1) tài khoản trên Nền Tảng</li><li>Bạn sẽ tuân thủ tất cả các luật hiện hành của Việt Nam khi sử dụng dịch vụ</li></ul></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">5. Mô Tả Dịch Vụ</h2><p className="mb-3">LÒ ĐỒ ĂN là nền tảng đặt hàng thực phẩm trực tuyến kết nối Người Dùng với các Nhà Hàng đối tác. Ovenly cung cấp công nghệ để:</p><ul className="list-disc list-inside space-y-2"><li>Hiển thị thực đơn và giá cả từ các Nhà Hàng</li><li>Xử lý đơn đặt hàng từ Người Dùng đến Nhà Hàng</li><li>Tạo điều kiện thanh toán trực tuyến</li><li>Cung cấp thông tin về trạng thái đơn hàng</li></ul><p className="mt-3"><strong>Lưu ý quan trọng:</strong> Ovenly KHÔNG chịu trách nhiệm về chất lượng thực phẩm, độ an toàn thực phẩm, thời gian chế biến, hoặc dịch vụ của Nhà Hàng. Tất cả các vấn đề liên quan đến thực phẩm là trách nhiệm của Nhà Hàng.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">6. Tài Khoản Người Dùng</h2><p className="mb-3">Bạn có thể tạo tài khoản để:</p><ul className="list-disc list-inside space-y-1 mb-3"><li>Lưu địa chỉ giao hàng</li><li>Xem lịch sử đơn hàng</li><li>Sử dụng mã giảm giá</li><li>Nhận thông báo về đơn hàng</li></ul><p>Bạn chịu trách nhiệm duy trì tính bảo mật của tài khoản. Ovenly có quyền đình chỉ hoặc chấm dứt tài khoản nếu phát hiện vi phạm Điều Khoản này hoặc hoạt động gian lận.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">7. Đặt Hàng và Xác Nhận</h2><p className="mb-3">Quy trình đặt hàng:</p><ol className="list-decimal list-inside space-y-2 mb-3"><li>Người Dùng chọn món ăn và đặt hàng trên Nền Tảng</li><li>Nhà Hàng nhận thông báo và xác nhận đơn hàng</li><li>Nhà Hàng chế biến và chuẩn bị đơn hàng</li><li>Người Dùng nhận hàng (tại quầy hoặc giao hàng)</li></ol><p><strong>Quan trọng:</strong> Đơn hàng chỉ được xem là hợp lệ sau khi Nhà Hàng xác nhận. Nhà Hàng có quyền từ chối đơn hàng trong trường hợp hết hàng, ngoài giờ phục vụ, hoặc lý do hợp lý khác.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">8. Giá Cả và Thanh Toán</h2><p className="mb-3">Tất cả giá cả được hiển thị bằng đồng Việt Nam (VNĐ) và đã bao gồm thuế GTGT.</p><p className="mb-3"><strong>Cấu thành giá đơn hàng:</strong></p><ul className="list-disc list-inside space-y-2 mb-3"><li><strong>Giá món ăn:</strong> Do Nhà Hàng quy định</li><li><strong>Phí dịch vụ:</strong> Phí Ovenly thu để vận hành Nền Tảng (1-2% giá trị đơn hàng)</li><li><strong>Phí giao hàng:</strong> Nếu chọn giao hàng (do Nhà Hàng quy định)</li></ul><p className="mb-3"><strong>Phương thức thanh toán:</strong></p><ul className="list-disc list-inside space-y-1"><li>Tiền mặt khi nhận hàng (COD)</li><li>Chuyển khoản ngân hàng</li><li>Ví điện tử (MoMo, ZaloPay, VNPay)</li></ul></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">9. Chính Sách Hủy Đơn và Hoàn Tiền</h2><p className="mb-3"><strong>Người Dùng hủy đơn:</strong></p><ul className="list-disc list-inside space-y-2 mb-3"><li>Trước khi Nhà Hàng xác nhận: Hoàn tiền 100%</li><li>Sau khi Nhà Hàng xác nhận: Không hoàn tiền (Nhà Hàng đã bắt đầu chế biến)</li><li>Thanh toán trực tuyến: Hoàn tiền trong 5-7 ngày làm việc</li></ul><p className="mb-3"><strong>Nhà Hàng hủy đơn:</strong></p><p>Nếu Nhà Hàng hủy đơn sau khi xác nhận, Người Dùng được hoàn tiền 100% trong vòng 24 giờ.</p><p className="mb-3"><strong>Khiếu nại chất lượng:</strong></p><p>Nếu có vấn đề về chất lượng thực phẩm, vui lòng liên hệ <a href="mailto:hello@ovenly.io" className="text-primary underline font-semibold">hello@ovenly.io</a> trong vòng 24 giờ kèm hình ảnh. Chúng tôi sẽ làm việc với Nhà Hàng để giải quyết.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">10. Nghĩa Vụ Của Nhà Hàng</h2><p className="mb-2">Nhà Hàng đăng ký trên Nền Tảng cam kết:</p><ul className="list-disc list-inside space-y-2"><li>Có đầy đủ giấy phép kinh doanh và giấy chứng nhận an toàn thực phẩm theo quy định pháp luật Việt Nam</li><li><strong>Phát hành hóa đơn GTGT hoặc hóa đơn bán hàng</strong> cho mỗi đơn hàng theo Luật Thuế và quy định của Tổng cục Thuế</li><li>Đảm bảo chất lượng và an toàn thực phẩm</li><li>Chế biến đơn hàng đúng thời gian cam kết</li><li>Chịu trách nhiệm hoàn toàn về chất lượng món ăn được cung cấp</li></ul><p className="mt-3 text-sm text-gray-600">Ovenly có quyền tạm ngưng hoặc chấm dứt hợp tác với Nhà Hàng vi phạm các nghĩa vụ trên.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">11. Đánh Giá và Nhận Xét</h2><p>Người Dùng có thể đánh giá và để lại nhận xét về Nhà Hàng sau khi hoàn thành đơn hàng. Bạn đồng ý:</p><ul className="list-disc list-inside space-y-2 mt-2"><li>Đánh giá phải trung thực, dựa trên trải nghiệm thực tế</li><li>Không sử dụng ngôn ngữ thô tục, xúc phạm, hoặc phân biệt đối xử</li><li>Ovenly có quyền gỡ bỏ đánh giá vi phạm mà không cần thông báo trước</li></ul></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">12. Quyền Sở Hữu Trí Tuệ</h2><p className="mb-3">Nền Tảng LÒ ĐỒ ĂN, bao gồm thiết kế, logo, mã nguồn, và nội dung là tài sản trí tuệ của Ovenly và được bảo vệ bởi luật sở hữu trí tuệ Việt Nam.</p><p>Bạn không được:</p><ul className="list-disc list-inside space-y-1 mt-2"><li>Sao chép, sửa đổi, hoặc phân phối bất kỳ phần nào của Nền Tảng</li><li>Sử dụng tên, logo LÒ ĐỒ ĂN cho mục đích thương mại mà không có sự cho phép</li><li>Dịch ngược, tháo rời, hoặc cố gắng trích xuất mã nguồn</li></ul></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">13. Bảo Vệ Dữ Liệu Cá Nhân</h2><p className="mb-3">Việc thu thập, sử dụng và bảo vệ Dữ Liệu Cá Nhân của bạn tuân thủ <a href="/privacy" target="_blank" rel="noopener noreferrer" className="text-primary underline font-semibold">Chính Sách Bảo Mật</a> của chúng tôi và Luật Bảo Vệ Dữ Liệu Cá Nhân số 91/2025/QH15.</p><p>Bằng việc sử dụng Nền Tảng, bạn đồng ý cho Ovenly:</p><ul className="list-disc list-inside space-y-1 mt-2"><li>Thu thập và xử lý Dữ Liệu Cá Nhân để cung cấp dịch vụ</li><li>Chia sẻ thông tin cần thiết với Nhà Hàng để xử lý đơn hàng</li><li>Lưu trữ dữ liệu trên máy chủ tại Hoa Kỳ và Singapore</li></ul></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">14. Giới Hạn Trách Nhiệm</h2><p className="mb-3"><strong>Ovenly KHÔNG chịu trách nhiệm về:</strong></p><ul className="list-disc list-inside space-y-2"><li>Chất lượng, độ an toàn, hoặc độ tươi ngon của thực phẩm do Nhà Hàng cung cấp</li><li>Hành vi, dịch vụ, hoặc thiếu sót của Nhà Hàng</li><li>Ngộ độc thực phẩm hoặc vấn đề sức khỏe liên quan đến thực phẩm</li><li>Thời gian chế biến hoặc giao hàng chậm do Nhà Hàng</li><li>Tranh chấp giữa Người Dùng và Nhà Hàng về chất lượng món ăn</li><li>Gián đoạn dịch vụ do sự cố kỹ thuật, bảo trì, hoặc yếu tố bất khả kháng</li></ul><p className="mt-3">Trách nhiệm tối đa của Ovenly không vượt quá giá trị đơn hàng bị ảnh hưởng.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">15. Bồi Thường</h2><p>Bạn đồng ý bồi thường và giữ cho Ovenly, các giám đốc, nhân viên, và đối tác của Ovenly không bị tổn hại khỏi mọi khiếu nại, tổn thất, thiệt hại, chi phí (bao gồm phí luật sư) phát sinh từ:</p><ul className="list-disc list-inside space-y-1 mt-2"><li>Việc bạn vi phạm Điều Khoản Dịch Vụ này</li><li>Việc bạn vi phạm pháp luật Việt Nam</li><li>Việc bạn vi phạm quyền của bên thứ ba</li><li>Việc bạn sử dụng Nền Tảng sai mục đích hoặc gây hại</li></ul></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">16. Giải Quyết Tranh Chấp</h2><p className="mb-3">Bất kỳ tranh chấp nào phát sinh từ hoặc liên quan đến Điều Khoản này sẽ được giải quyết theo quy trình sau:</p><ol className="list-decimal list-inside space-y-2"><li>Thương lượng trực tiếp giữa các bên trong vòng 30 ngày</li><li>Nếu không thỏa thuận được, tranh chấp sẽ được giải quyết tại Trung tâm Trọng tài Quốc tế Việt Nam (VIAC)</li><li>Luật điều chỉnh: Pháp luật nước Cộng hòa Xã hội Chủ nghĩa Việt Nam</li><li>Ngôn ngữ trọng tài: Tiếng Việt</li></ol></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">17. Thay Đổi Điều Khoản</h2><p>Ovenly có quyền sửa đổi Điều Khoản Dịch Vụ này bất kỳ lúc nào. Các thay đổi sẽ được thông báo qua Nền Tảng và/hoặc email ít nhất 5 ngày trước khi có hiệu lực. Việc bạn tiếp tục sử dụng Nền Tảng sau khi thay đổi có hiệu lực đồng nghĩa với việc bạn chấp nhận các điều khoản mới.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">18. Điều Khoản Chung</h2><p className="mb-2">Nếu bất kỳ điều khoản nào trong văn bản này bị coi là không hợp lệ hoặc không thể thi hành, các điều khoản còn lại vẫn có hiệu lực đầy đủ.</p><p>Ovenly có quyền chuyển nhượng quyền và nghĩa vụ theo Điều Khoản này cho bên thứ ba mà không cần sự đồng ý của bạn.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">19. Thông Tin Liên Hệ</h2><p className="mb-2">Nếu bạn có câu hỏi về Điều Khoản Dịch Vụ này, vui lòng liên hệ:</p><p><strong>Ovenly</strong><br/>Email: <a href="mailto:hello@ovenly.io" className="text-primary underline font-semibold">hello@ovenly.io</a><br/>Website: <a href="https://www.lodoan.vn" target="_blank" rel="noopener noreferrer" className="text-primary underline">www.lodoan.vn</a></p></section>
          </>) : (<>
            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">1. Introduction and Acceptance of Terms</h2><p className="mb-3">Please read these Terms of Service carefully. By accessing and using the LÒ ĐỒ ĂN platform ("Platform"), you agree that you have read, understood, and accept to be bound by these terms.</p><p className="mb-3"><strong>Ovenly</strong> is the technology company that provides and operates the LÒ ĐỒ ĂN Platform. When mentioned in this document, "we", "our" or "Ovenly" all refer to Ovenly company.</p><p><strong>IMPORTANT: OVENLY IS A TECHNOLOGY PLATFORM</strong> connecting customers with partner restaurants. OVENLY IS NOT A RESTAURANT, DOES NOT PREPARE FOOD, AND IS NOT THE DIRECT SELLER. Ovenly's role is to provide the platform for customers to order from independent restaurants.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">2. Definitions</h2><ul className="list-disc list-inside space-y-2"><li><strong>Platform:</strong> The LÒ ĐỒ ĂN web and mobile application provided by Ovenly</li><li><strong>User:</strong> Customers using the Platform to order food</li><li><strong>Restaurant:</strong> Food businesses registered to sell on the Platform</li><li><strong>Order:</strong> Food purchase request placed through the Platform</li><li><strong>Service Fee:</strong> Fee charged by Ovenly to maintain and operate the Platform</li><li><strong>Personal Data:</strong> Personally identifiable information under the Personal Data Protection Law</li></ul></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">3. Age and Legal Capacity Requirements</h2><p>You must be 18 years or older to use the Platform. By using the service, you warrant that you have full legal capacity to enter into contracts under Vietnamese law.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">4. User Warranties and Obligations</h2><p className="mb-2">When using the Platform, you warrant and agree that:</p><ul className="list-disc list-inside space-y-2"><li>All information you provide is true, accurate, and complete</li><li>You will keep your account password secure and notify us immediately of any unauthorized use</li><li>You will only use the Platform for lawful and personal purposes</li><li>You will not attempt to disrupt, damage, or gain unauthorized access to the Platform</li><li>You will not use the Platform to send unlawful, unethical content, or harm others</li><li>You will only create one (1) account on the Platform</li><li>You will comply with all applicable laws of Vietnam when using the service</li></ul></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">5. Service Description</h2><p className="mb-3">LÒ ĐỒ ĂN is an online food ordering platform connecting Users with partner Restaurants. Ovenly provides technology to:</p><ul className="list-disc list-inside space-y-2"><li>Display menus and prices from Restaurants</li><li>Process orders from Users to Restaurants</li><li>Facilitate online payments</li><li>Provide order status information</li></ul><p className="mt-3"><strong>Important note:</strong> Ovenly is NOT responsible for food quality, food safety, preparation time, or Restaurant service. All food-related issues are the Restaurant's responsibility.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">6. User Accounts</h2><p className="mb-3">You may create an account to:</p><ul className="list-disc list-inside space-y-1 mb-3"><li>Save delivery addresses</li><li>View order history</li><li>Use promo codes</li><li>Receive order notifications</li></ul><p>You are responsible for maintaining account security. Ovenly may suspend or terminate accounts for violations of these Terms or fraudulent activity.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">7. Orders and Confirmation</h2><p className="mb-3">Order process:</p><ol className="list-decimal list-inside space-y-2 mb-3"><li>User selects food and places order on Platform</li><li>Restaurant receives notification and confirms order</li><li>Restaurant prepares order</li><li>User receives order (pickup or delivery)</li></ol><p><strong>Important:</strong> Orders are only valid after Restaurant confirmation. Restaurants may decline orders if items are unavailable, outside operating hours, or for other reasonable reasons.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">8. Pricing and Payment</h2><p className="mb-3">All prices displayed in Vietnamese Dong (VND) including VAT.</p><p className="mb-3"><strong>Order total breakdown:</strong></p><ul className="list-disc list-inside space-y-2 mb-3"><li><strong>Food price:</strong> Set by Restaurant</li><li><strong>Service fee:</strong> Fee charged by Ovenly to operate Platform (1-2% of order value)</li><li><strong>Delivery fee:</strong> If delivery selected (set by Restaurant)</li></ul><p className="mb-3"><strong>Payment methods:</strong></p><ul className="list-disc list-inside space-y-1"><li>Cash on delivery (COD)</li><li>Bank transfer</li><li>E-wallets (MoMo, ZaloPay, VNPay)</li></ul></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">9. Cancellation and Refund Policy</h2><p className="mb-3"><strong>User cancellations:</strong></p><ul className="list-disc list-inside space-y-2 mb-3"><li>Before Restaurant confirmation: 100% refund</li><li>After Restaurant confirmation: No refund (Restaurant has started preparation)</li><li>Online payments: Refund within 5-7 business days</li></ul><p className="mb-3"><strong>Restaurant cancellations:</strong></p><p>If Restaurant cancels after confirmation, User receives 100% refund within 24 hours.</p><p className="mb-3"><strong>Quality complaints:</strong></p><p>For food quality issues, contact <a href="mailto:hello@ovenly.io" className="text-primary underline font-semibold">hello@ovenly.io</a> within 24 hours with photos. We will work with the Restaurant to resolve.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">10. Restaurant Obligations</h2><p className="mb-2">Restaurants registered on the Platform commit to:</p><ul className="list-disc list-inside space-y-2"><li>Having all required business licenses and food safety certificates per Vietnamese law</li><li><strong>Issuing VAT invoices or sales invoices</strong> for each order per Tax Law and General Department of Taxation regulations</li><li>Ensuring food quality and safety</li><li>Preparing orders within committed timeframes</li><li>Taking full responsibility for the quality of food provided</li></ul><p className="mt-3 text-sm text-gray-600">Ovenly may suspend or terminate partnership with Restaurants violating these obligations.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">11. Ratings and Reviews</h2><p>Users may rate and review Restaurants after order completion. You agree:</p><ul className="list-disc list-inside space-y-2 mt-2"><li>Reviews must be truthful, based on actual experience</li><li>Not to use profane, offensive, or discriminatory language</li><li>Ovenly may remove violating reviews without notice</li></ul></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">12. Intellectual Property Rights</h2><p className="mb-3">The LÒ ĐỒ ĂN Platform, including design, logo, source code, and content is Ovenly's intellectual property and protected by Vietnamese IP law.</p><p>You may not:</p><ul className="list-disc list-inside space-y-1 mt-2"><li>Copy, modify, or distribute any part of the Platform</li><li>Use the LÒ ĐỒ ĂN name, logo commercially without permission</li><li>Reverse engineer, disassemble, or attempt to extract source code</li></ul></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">13. Personal Data Protection</h2><p className="mb-3">Collection, use, and protection of your Personal Data complies with our <a href="/privacy" target="_blank" rel="noopener noreferrer" className="text-primary underline font-semibold">Privacy Policy</a> and Personal Data Protection Law No. 91/2025/QH15.</p><p>By using the Platform, you consent to Ovenly:</p><ul className="list-disc list-inside space-y-1 mt-2"><li>Collecting and processing Personal Data to provide services</li><li>Sharing necessary information with Restaurants to process orders</li><li>Storing data on servers in the United States and Singapore</li></ul></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">14. Limitation of Liability</h2><p className="mb-3"><strong>Ovenly is NOT responsible for:</strong></p><ul className="list-disc list-inside space-y-2"><li>Quality, safety, or freshness of food provided by Restaurants</li><li>Restaurant conduct, service, or omissions</li><li>Food poisoning or health issues related to food</li><li>Restaurant preparation or delivery delays</li><li>Disputes between Users and Restaurants about food quality</li><li>Service interruptions due to technical issues, maintenance, or force majeure</li></ul><p className="mt-3">Ovenly's maximum liability does not exceed the affected order value.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">15. Indemnification</h2><p>You agree to indemnify and hold Ovenly, its directors, employees, and partners harmless from all claims, losses, damages, costs (including attorney fees) arising from:</p><ul className="list-disc list-inside space-y-1 mt-2"><li>Your violation of these Terms of Service</li><li>Your violation of Vietnamese law</li><li>Your violation of third-party rights</li><li>Your misuse of the Platform or causing harm</li></ul></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">16. Dispute Resolution</h2><p className="mb-3">Any disputes arising from or related to these Terms shall be resolved through:</p><ol className="list-decimal list-inside space-y-2"><li>Direct negotiation between parties within 30 days</li><li>If no agreement, dispute will be resolved at Vietnam International Arbitration Centre (VIAC)</li><li>Governing law: Laws of the Socialist Republic of Vietnam</li><li>Arbitration language: Vietnamese</li></ol></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">17. Changes to Terms</h2><p>Ovenly may modify these Terms of Service at any time. Changes will be notified via the Platform and/or email at least 5 days before taking effect. Your continued use of the Platform after changes take effect constitutes acceptance of the new terms.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">18. General Provisions</h2><p className="mb-2">If any provision is deemed invalid or unenforceable, the remaining provisions remain in full effect.</p><p>Ovenly may assign rights and obligations under these Terms to third parties without your consent.</p></section>

            <section><h2 className="font-heading font-bold text-lg text-gray-900 mb-3">19. Contact Information</h2><p className="mb-2">For questions about these Terms of Service, please contact:</p><p><strong>Ovenly</strong><br/>Email: <a href="mailto:hello@ovenly.io" className="text-primary underline font-semibold">hello@ovenly.io</a><br/>Website: <a href="https://www.lodoan.vn" target="_blank" rel="noopener noreferrer" className="text-primary underline">www.lodoan.vn</a></p></section>
          </>)}
        </div>
      </div>
    </div>
  );
}